export const LANGUAGES = [
  { friendlyName: "Acehnese (Arabic script)", languageCode: "ace_Arab" },
  { friendlyName: "Acehnese (Latin script)", languageCode: "ace_Latn" },
  { friendlyName: "Afrikaans", languageCode: "afr_Latn" },
  { friendlyName: "Akan", languageCode: "aka_Latn" },
  { friendlyName: "Amharic", languageCode: "amh_Ethi" },
  { friendlyName: "Armenian", languageCode: "hye_Armn" },
  { friendlyName: "Assamese", languageCode: "asm_Beng" },
  { friendlyName: "Asturian", languageCode: "ast_Latn" },
  { friendlyName: "Awadhi", languageCode: "awa_Deva" },
  { friendlyName: "Ayacucho Quechua", languageCode: "quy_Latn" },
  { friendlyName: "Balinese", languageCode: "ban_Latn" },
  { friendlyName: "Bambara", languageCode: "bam_Latn" },
  { friendlyName: "Banjar (Arabic script)", languageCode: "bjn_Arab" },
  { friendlyName: "Banjar (Latin script)", languageCode: "bjn_Latn" },
  { friendlyName: "Bashkir", languageCode: "bak_Cyrl" },
  { friendlyName: "Basque", languageCode: "eus_Latn" },
  { friendlyName: "Belarusian", languageCode: "bel_Cyrl" },
  { friendlyName: "Bemba", languageCode: "bem_Latn" },
  { friendlyName: "Bengali", languageCode: "ben_Beng" },
  { friendlyName: "Bhojpuri", languageCode: "bho_Deva" },
  { friendlyName: "Bosnian", languageCode: "bos_Latn" },
  { friendlyName: "Buginese", languageCode: "bug_Latn" },
  { friendlyName: "Bulgarian", languageCode: "bul_Cyrl" },
  { friendlyName: "Burmese", languageCode: "mya_Mymr" },
  { friendlyName: "Catalan", languageCode: "cat_Latn" },
  { friendlyName: "Cebuano", languageCode: "ceb_Latn" },
  { friendlyName: "Central Atlas Tamazight", languageCode: "tzm_Tfng" },
  { friendlyName: "Central Aymara", languageCode: "ayr_Latn" },
  { friendlyName: "Central Kanuri (Arabic script)", languageCode: "knc_Arab" },
  { friendlyName: "Central Kanuri (Latin script)", languageCode: "knc_Latn" },
  { friendlyName: "Central Kurdish", languageCode: "ckb_Arab" },
  { friendlyName: "Chhattisgarhi", languageCode: "hne_Deva" },
  { friendlyName: "Chinese (Simplified)", languageCode: "zho_Hans" },
  { friendlyName: "Chinese (Traditional)", languageCode: "zho_Hant" },
  { friendlyName: "Chokwe", languageCode: "cjk_Latn" },
  { friendlyName: "Crimean Tatar", languageCode: "crh_Latn" },
  { friendlyName: "Croatian", languageCode: "hrv_Latn" },
  { friendlyName: "Czech", languageCode: "ces_Latn" },
  { friendlyName: "Danish", languageCode: "dan_Latn" },
  { friendlyName: "Dari", languageCode: "prs_Arab" },
  { friendlyName: "Dutch", languageCode: "nld_Latn" },
  { friendlyName: "Dyula", languageCode: "dyu_Latn" },
  { friendlyName: "Dzongkha", languageCode: "dzo_Tibt" },
  { friendlyName: "Eastern Panjabi", languageCode: "pan_Guru" },
  { friendlyName: "Eastern Yiddish", languageCode: "ydd_Hebr" },
  { friendlyName: "Egyptian Arabic", languageCode: "arz_Arab" },
  { friendlyName: "English", languageCode: "eng_Latn" },
  { friendlyName: "Esperanto", languageCode: "epo_Latn" },
  { friendlyName: "Estonian", languageCode: "est_Latn" },
  { friendlyName: "Ewe", languageCode: "ewe_Latn" },
  { friendlyName: "Faroese", languageCode: "fao_Latn" },
  { friendlyName: "Fijian", languageCode: "fij_Latn" },
  { friendlyName: "Finnish", languageCode: "fin_Latn" },
  { friendlyName: "Fon", languageCode: "fon_Latn" },
  { friendlyName: "French", languageCode: "fra_Latn" },
  { friendlyName: "Friulian", languageCode: "fur_Latn" },
  { friendlyName: "Galician", languageCode: "glg_Latn" },
  { friendlyName: "Ganda", languageCode: "lug_Latn" },
  { friendlyName: "Georgian", languageCode: "kat_Geor" },
  { friendlyName: "German", languageCode: "deu_Latn" },
  { friendlyName: "Greek", languageCode: "ell_Grek" },
  { friendlyName: "Guarani", languageCode: "grn_Latn" },
  { friendlyName: "Gujarati", languageCode: "guj_Gujr" },
  { friendlyName: "Haitian Creole", languageCode: "hat_Latn" },
  { friendlyName: "Halh Mongolian", languageCode: "khk_Cyrl" },
  { friendlyName: "Hausa", languageCode: "hau_Latn" },
  { friendlyName: "Hebrew", languageCode: "heb_Hebr" },
  { friendlyName: "Hindi", languageCode: "hin_Deva" },
  { friendlyName: "Hungarian", languageCode: "hun_Latn" },
  { friendlyName: "Icelandic", languageCode: "isl_Latn" },
  { friendlyName: "Igbo", languageCode: "ibo_Latn" },
  { friendlyName: "Ilocano", languageCode: "ilo_Latn" },
  { friendlyName: "Indonesian", languageCode: "ind_Latn" },
  { friendlyName: "Irish", languageCode: "gle_Latn" },
  { friendlyName: "Italian", languageCode: "ita_Latn" },
  { friendlyName: "Japanese", languageCode: "jpn_Jpan" },
  { friendlyName: "Javanese", languageCode: "jav_Latn" },
  { friendlyName: "Jingpho", languageCode: "kac_Latn" },
  { friendlyName: "Kabiyè", languageCode: "kbp_Latn" },
  { friendlyName: "Kabuverdianu", languageCode: "kea_Latn" },
  { friendlyName: "Kabyle", languageCode: "kab_Latn" },
  { friendlyName: "Kamba", languageCode: "kam_Latn" },
  { friendlyName: "Kannada", languageCode: "kan_Knda" },
  { friendlyName: "Kashmiri (Arabic script)", languageCode: "kas_Arab" },
  { friendlyName: "Kashmiri (Devanagari script)", languageCode: "kas_Deva" },
  { friendlyName: "Kazakh", languageCode: "kaz_Cyrl" },
  { friendlyName: "Khmer", languageCode: "khm_Khmr" },
  { friendlyName: "Kikongo", languageCode: "kon_Latn" },
  { friendlyName: "Kikuyu", languageCode: "kik_Latn" },
  { friendlyName: "Kimbundu", languageCode: "kmb_Latn" },
  { friendlyName: "Kinyarwanda", languageCode: "kin_Latn" },
  { friendlyName: "Korean", languageCode: "kor_Hang" },
  { friendlyName: "Kyrgyz", languageCode: "kir_Cyrl" },
  { friendlyName: "Lao", languageCode: "lao_Laoo" },
  { friendlyName: "Latgalian", languageCode: "ltg_Latn" },
  { friendlyName: "Ligurian", languageCode: "lij_Latn" },
  { friendlyName: "Limburgish", languageCode: "lim_Latn" },
  { friendlyName: "Lingala", languageCode: "lin_Latn" },
  { friendlyName: "Lithuanian", languageCode: "lit_Latn" },
  { friendlyName: "Lombard", languageCode: "lmo_Latn" },
  { friendlyName: "Luba-Kasai", languageCode: "lua_Latn" },
  { friendlyName: "Luo", languageCode: "luo_Latn" },
  { friendlyName: "Luxembourgish", languageCode: "ltz_Latn" },
  { friendlyName: "Macedonian", languageCode: "mkd_Cyrl" },
  { friendlyName: "Magahi", languageCode: "mag_Deva" },
  { friendlyName: "Maithili", languageCode: "mai_Deva" },
  { friendlyName: "Malayalam", languageCode: "mal_Mlym" },
  { friendlyName: "Maltese", languageCode: "mlt_Latn" },
  { friendlyName: "Maori", languageCode: "mri_Latn" },
  { friendlyName: "Marathi", languageCode: "mar_Deva" },
  { friendlyName: "Meitei (Bengali script)", languageCode: "mni_Beng" },
  { friendlyName: "Mesopotamian Arabic", languageCode: "acm_Arab" },
  { friendlyName: "Minangkabau (Arabic script)", languageCode: "min_Arab" },
  { friendlyName: "Minangkabau (Latin script)", languageCode: "min_Latn" },
  { friendlyName: "Mizo", languageCode: "lus_Latn" },
  { friendlyName: "Modern Standard Arabic (Romanized)", languageCode: "arb_Latn" },
  { friendlyName: "Modern Standard Arabic", languageCode: "arb_Arab" },
  { friendlyName: "Moroccan Arabic", languageCode: "ary_Arab" },
  { friendlyName: "Mossi", languageCode: "mos_Latn" },
  { friendlyName: "Najdi Arabic", languageCode: "ars_Arab" },
  { friendlyName: "Nepali", languageCode: "npi_Deva" },
  { friendlyName: "Nigerian Fulfulde", languageCode: "fuv_Latn" },
  { friendlyName: "North Azerbaijani", languageCode: "azj_Latn" },
  { friendlyName: "North Levantine Arabic", languageCode: "apc_Arab" },
  { friendlyName: "Northern Kurdish", languageCode: "kmr_Latn" },
  { friendlyName: "Northern Sotho", languageCode: "nso_Latn" },
  { friendlyName: "Northern Uzbek", languageCode: "uzn_Latn" },
  { friendlyName: "Norwegian Bokmål", languageCode: "nob_Latn" },
  { friendlyName: "Norwegian Nynorsk", languageCode: "nno_Latn" },
  { friendlyName: "Nuer", languageCode: "nus_Latn" },
  { friendlyName: "Nyanja", languageCode: "nya_Latn" },
  { friendlyName: "Occitan", languageCode: "oci_Latn" },
  { friendlyName: "Odia", languageCode: "ory_Orya" },
  { friendlyName: "Pangasinan", languageCode: "pag_Latn" },
  { friendlyName: "Papiamento", languageCode: "pap_Latn" },
  { friendlyName: "Plateau Malagasy", languageCode: "plt_Latn" },
  { friendlyName: "Polish", languageCode: "pol_Latn" },
  { friendlyName: "Portuguese", languageCode: "por_Latn" },
  { friendlyName: "Romanian", languageCode: "ron_Latn" },
  { friendlyName: "Rundi", languageCode: "run_Latn" },
  { friendlyName: "Russian", languageCode: "rus_Cyrl" },
  { friendlyName: "Samoan", languageCode: "smo_Latn" },
  { friendlyName: "Sango", languageCode: "sag_Latn" },
  { friendlyName: "Sanskrit", languageCode: "san_Deva" },
  { friendlyName: "Santali", languageCode: "sat_Olck" },
  { friendlyName: "Sardinian", languageCode: "srd_Latn" },
  { friendlyName: "Scottish Gaelic", languageCode: "gla_Latn" },
  { friendlyName: "Serbian", languageCode: "srp_Cyrl" },
  { friendlyName: "Shan", languageCode: "shn_Mymr" },
  { friendlyName: "Shona", languageCode: "sna_Latn" },
  { friendlyName: "Sicilian", languageCode: "scn_Latn" },
  { friendlyName: "Silesian", languageCode: "szl_Latn" },
  { friendlyName: "Sindhi", languageCode: "snd_Arab" },
  { friendlyName: "Sinhala", languageCode: "sin_Sinh" },
  { friendlyName: "Slovak", languageCode: "slk_Latn" },
  { friendlyName: "Slovenian", languageCode: "slv_Latn" },
  { friendlyName: "Somali", languageCode: "som_Latn" },
  { friendlyName: "South Azerbaijani", languageCode: "azb_Arab" },
  { friendlyName: "South Levantine Arabic", languageCode: "ajp_Arab" },
  { friendlyName: "Southern Pashto", languageCode: "pbt_Arab" },
  { friendlyName: "Southern Sotho", languageCode: "sot_Latn" },
  { friendlyName: "Southwestern Dinka", languageCode: "dik_Latn" },
  { friendlyName: "Spanish", languageCode: "spa_Latn" },
  { friendlyName: "Standard Latvian", languageCode: "lvs_Latn" },
  { friendlyName: "Standard Malay", languageCode: "zsm_Latn" },
  { friendlyName: "Standard Tibetan", languageCode: "bod_Tibt" },
  { friendlyName: "Sundanese", languageCode: "sun_Latn" },
  { friendlyName: "Swahili", languageCode: "swh_Latn" },
  { friendlyName: "Swati", languageCode: "ssw_Latn" },
  { friendlyName: "Swedish", languageCode: "swe_Latn" },
  { friendlyName: "Tagalog", languageCode: "tgl_Latn" },
  { friendlyName: "Tajik", languageCode: "tgk_Cyrl" },
  { friendlyName: "Tamasheq (Latin script)", languageCode: "taq_Latn" },
  { friendlyName: "Tamasheq (Tifinagh script)", languageCode: "taq_Tfng" },
  { friendlyName: "Tamil", languageCode: "tam_Taml" },
  { friendlyName: "Tatar", languageCode: "tat_Cyrl" },
  { friendlyName: "Ta’izzi-Adeni Arabic", languageCode: "acq_Arab" },
  { friendlyName: "Telugu", languageCode: "tel_Telu" },
  { friendlyName: "Thai", languageCode: "tha_Thai" },
  { friendlyName: "Tigrinya", languageCode: "tir_Ethi" },
  { friendlyName: "Tok Pisin", languageCode: "tpi_Latn" },
  { friendlyName: "Tosk Albanian", languageCode: "als_Latn" },
  { friendlyName: "Tsonga", languageCode: "tso_Latn" },
  { friendlyName: "Tswana", languageCode: "tsn_Latn" },
  { friendlyName: "Tumbuka", languageCode: "tum_Latn" },
  { friendlyName: "Tunisian Arabic", languageCode: "aeb_Arab" },
  { friendlyName: "Turkish", languageCode: "tur_Latn" },
  { friendlyName: "Turkmen", languageCode: "tuk_Latn" },
  { friendlyName: "Twi", languageCode: "twi_Latn" },
  { friendlyName: "Ukrainian", languageCode: "ukr_Cyrl" },
  { friendlyName: "Umbundu", languageCode: "umb_Latn" },
  { friendlyName: "Urdu", languageCode: "urd_Arab" },
  { friendlyName: "Uyghur", languageCode: "uig_Arab" },
  { friendlyName: "Venetian", languageCode: "vec_Latn" },
  { friendlyName: "Vietnamese", languageCode: "vie_Latn" },
  { friendlyName: "Waray", languageCode: "war_Latn" },
  { friendlyName: "Welsh", languageCode: "cym_Latn" },
  { friendlyName: "West Central Oromo", languageCode: "gaz_Latn" },
  { friendlyName: "Western Persian", languageCode: "pes_Arab" },
  { friendlyName: "Wolof", languageCode: "wol_Latn" },
  { friendlyName: "Xhosa", languageCode: "xho_Latn" },
  { friendlyName: "Yoruba", languageCode: "yor_Latn" },
  { friendlyName: "Yue Chinese", languageCode: "yue_Hant" },
  { friendlyName: "Zulu", languageCode: "zul_Latn" }
]